name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]  # change to 'master' if that's your default branch
  workflow_dispatch:  # allows manual deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.13.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.3'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hei-sopchatbot-dev'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
